spring.application.name=SatvaRasaBackend

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/satvarasa_db
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server
server.port=8080